In [5]:
!python --version

Python 3.12.1


### Q1. Pandas version

What's the version of Pandas that you installed?

You can get the version information using the `__version__` field:

```python
pd.__version__
```

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.2'

### Getting the data 

For this homework, we'll use the Car Fuel Efficiency dataset. Download it from <a href='https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv'>here</a>.

You can do it with wget:
```bash
wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
```

Or just open it with your browser and click "Save as...".

Now read it with Pandas.

### Q2. Records count

How many records are in the dataset?

- 4704
- 8704
- 9704 <---
- 17704

In [8]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-28 20:23:15--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.007s  

2025-09-28 20:23:15 (120 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [9]:
!ls

Homework-01.ipynb  car_fuel_efficiency.csv  homework_qns.md


In [214]:
df = pd.read_csv('car_fuel_efficiency.csv')
row_count1 = len(df)
row_count2 = df.shape[0]
row_count3 = len(df.index)

(row_count1, row_count2, row_count3)

(9704, 9704, 9704)

### Q3. Fuel types

How many fuel types are presented in the dataset?

- 1
- 2 <---
- 3
- 4

In [28]:
unique_fuel_types = df['fuel_type'].unique()
no_unique_fuel_types = len(unique_fuel_types)
(unique_fuel_types, no_unique_fuel_types)

(array(['Gasoline', 'Diesel'], dtype=object), 2)

### Q4. Missing values

How many columns in the dataset have missing values?

- 0
- 1
- 2
- 3
- 4 <---

In [52]:
missing_values_per_column = df.isnull().sum()
missing_values_per_column

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [57]:
num_columns_with_missing_values = missing_values_per_column > 0
num_columns_with_missing_values.sum()

np.int64(4)

### Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

- 13.75
- 23.75 <---
- 33.75
- 43.75

In [41]:
df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max() # max        23.759123

np.float64(23.759122836520497)

### Q6. Median value of horsepower



1. Find the median value of `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use `fillna` method to fill the missing values in `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

Has it changed?


- Yes, it increased <---
- Yes, it decreased
- No

In [215]:
df.horsepower.median() # 149

np.float64(149.0)

In [216]:
df.horsepower.mode()[0] # 152

np.float64(152.0)

In [217]:
most_frequent_value_counts = df['horsepower'].value_counts().idxmax()
most_frequent_value_counts

np.float64(152.0)

In [218]:
df_original = df.copy()
df.horsepower

0       159.0
1        97.0
2        78.0
3         NaN
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [219]:
df.horsepower = df['horsepower'].fillna(df.horsepower.mode()[0])
df.horsepower

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [220]:
df_original.horsepower.median() # 149

np.float64(149.0)

In [221]:
df.horsepower.median()

np.float64(152.0)

### Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

- 0.051
- 0.51 <---
- 5.1
- 51

In [181]:
def complex_operation(matrix):
    print(matrix.T)
    matmul1 = np.matmul(matrix.T, matrix)
    matmul2 = matrix.T.dot(matrix)
    matmul3 = np.dot(matrix.T, matrix)
    matmul4 = matrix.T @ matrix
    inv_mat = np.linalg.inv(matmul1)
    y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
    
    next_step1 = np.matmul(inv_mat, matrix.T)
    w = next_step1 @ y
    #w = inv_mat @ matrix.T @ y

    result = w
    print(w.sum())

test_matrix = np.array([[1, 2],
                        [3, 4],
                        [5, 6],
                        [7, 8],
                        [9, 10],
                        [11, 12],
                        [13, 14]
                       ])
complex_operation(test_matrix)

[[ 1  3  5  7  9 11 13]
 [ 2  4  6  8 10 12 14]]
1.7857142857144481


In [182]:
df=df_original
df_to_matrix = df[df.origin == 'Asia'][['vehicle_weight','model_year']].head(7)
df_matrix = df_to_matrix.values

In [183]:
df_matrix

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [184]:
complex_operation(df_matrix)

[[2714.21930965 2783.86897424 3582.68736772 2231.8081416  2659.43145076
  2844.22753389 3761.99403819]
 [2016.         2010.         2007.         2011.         2016.
  2014.         2019.        ]]
0.5187709081074016
